version: '3.8'
services:
  db:
    image: postgres:16
    container_name: teamflow-db
    environment:
      POSTGRES_USER: teamflow
      POSTGRES_PASSWORD: teamflow123
      POSTGRES_DB: teamflow
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
